CREATE TABLE IF NOT EXISTS marca  (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bus  (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    numero_bus VARCHAR(50) NOT NULL,
    placa VARCHAR(20) NOT NULL UNIQUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    caracteristicas TEXT,
    activo BOOLEAN DEFAULT TRUE,
    marca_id BIGINT NOT NULL,
    CONSTRAINT fk_marca FOREIGN KEY (marca_id) REFERENCES marca(id) ON DELETE RESTRICT
);


